sudo: required
language: python
install: true
script: wget -O- https://raw.githubusercontent.com/dream-alpha/pybake/master/src/pybake.py
  | python - -i . -o $HOME
before_deploy: git tag 0.1.0
deploy:
  provider: releases
  api_key:
    secure: EqP0vTLTYyh8hUQCTjshNrR6FTA0eQYE2pZrMhm0+q39X/tXMaSA4QzU9xPCauVB/7InVAB4TzvCB1DD9VW/GgkMN0g3aTg4FxTA1+MtKMEy9XC0JGq8Nt4yTxGmWjhP0qdKO100DTXAiHzz1Uy1xZMdh8gOXkLffVuH6TIeKhvNvKn1KE6LskAiyLM/AyzDZ84TBv11AsS9cSNHPKWgFyrvXnKhKxsK9LL3ACyp39OMGb5sdZtbu2DEeoo7TQenH8pnZ1Fbyo6Y25S3IjPcOQuuZFiExGd9R0O0QQk/praP9eOhtKRmxviG5yxFLMaoJ2Z/fQ5jUN7S33grJyx8dsPuwO74bpuNGA9X/65r4AyqplruOf58s8Ynri9NaX6G2o9CNpriWQIZUvfUhquUpeKOq5aOY8ymq9dSE1AdvpwrV+SNpjEEMFcNsd44RVg/N6la107Gw2aSQJYZjTkbrCQZjWqq3pknjgcW3p0y6XBjbS8EL0JS3GiCfrIO9rJWGuaoKMwKB3aJ9zgUcMTc5/i4Oi4ypLQwSwpsAby640G9KWh1aBBvE9nD3ZPxTAD1EPkeQnxbSRADDu8ttERoBBTygIG2jTVGZMBPCtY79vMB8MnbBTBRlcjRO9uNhlb6BcAtlvJKNKL23UocGcjQcE1u7az+KfzK4+1fgWtrIAg=
  file: "$HOME/enigma2-plugin*"
  file_glob: true
  overwrite: true
  on:
    repo: dream-alpha/MediaCockpit
